### ISSUE TITLE
Link generation: sys.io.* links to cs.system.*

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/dox#292] opened 2021-11-03 02:31 UTC
Issues found with sys links pointing to cs.system docs at:
- `sys.io.Process` at https://api.haxe.org/Sys.html#command
- `sys.io.File` at https://api.haxe.org/sys/FileSystem.html

----

![image](https://user-images.githubusercontent.com/2192439/140002127-e1cc55e8-8e3c-4694-9657-d807247de6e7.png)

For some reason, `sys.io.Process` is linking to https://api.haxe.org/cs/system/diagnostics/Process.html#Process

The code looks fine: https://github.com/HaxeFoundation/haxe/blob/4.2.1/std/Sys.hx#L114

So I assume it's some problem in the generator.

**Comment by Gama11** [comment] 2021-11-03 10:12
Duplicate of https://github.com/HaxeFoundation/dox/issues/264

**Closed by Gama11** 2021-11-03 10:12 UTC
